
name: Build

on:  
  workflow_dispatch:
jobs:

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - name: build executable
        run: |
          cmake -GNinja .
          ninja
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: MDParse_MacOS
          path: ./MDParse*

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - name: build executable
        run: |
          cmake -GNinja .
          ninja
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: MDParse_Windows
          path: ./MDParse*

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - name: build executable
        run: |
          cmake -GNinja .
          ninja
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: MDParse_Ubuntu
          path: ./MDParse*
